apiVersion: v1
kind: Service
metadata:
  name: fastfood-app-service
  namespace: fastfood
  labels:
    app: fastfood-app
spec:
  selector:
    app: fastfood-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
