on:
  push:
    branches:
      - main
      - develop
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - ".github/workflows/**"

env:
  TF_VERSION: "1.5.0"
  AWS_REGION: "us-east-1" # Usar a Region de um secret

jobs:
  terraform-validate:
    name: "Terraform Validate"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ACTIONS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate
